ml:
  service:
    url: http://localhost:5000
server:
  port: 8080

spring:
  application:
    name: backend-transport
  datasource:
    url: jdbc:postgresql://10.139.168.97:5432/transport
    username: postgres
    password: Amy
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
